# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción

In [3]:
# cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
#Cargamos el modelo
import pickle
filename = 'modelo-reg.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

In [5]:
#Cargamos los datos futuros
#data = pd.read_csv("videojuegos-datosFuturos.csv")
#data.head()

In [6]:
# Aquí va la interfaz gráfica
#Interfaz gráfica

#Se crea interfaz gráfica con streamlit para captura de los datos



import streamlit as st



st.title('Predicción de inversión en una tienda de videojuegos')



Edad = st.slider('Edad', min_value=14, max_value=52, value=20, step=1)

videojuego = st.selectbox('Videojuego', ["'Mass Effect'","'Battlefield'", "'Fifa'","'KOA: Reckoning'","'Crysis'","'Sim City'","'Dead Space'","'F1'"])

Plataforma = st.selectbox('Plataforma', ["'Play Station'", "'Xbox'","PC","Otros"])

Sexo = st.selectbox('Sexo', ['Hombre', 'Mujer'])

Consumidor_habitual = st.selectbox('Consumidor_habitual', ['True', 'False'])





#Dataframe

datos = [[Edad, videojuego,Plataforma,Sexo,Consumidor_habitual]]

data = pd.DataFrame(datos, columns=['Edad', 'videojuego','Plataforma','Sexo','Consumidor_habitual']) #Dataframe con los mismos nombres de variables

2026-04-23 08:15:42.398 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.200
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\JUAN MANUEL PRETEL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-04-23 08:15:43.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.215 Session state does not function when running a script without `streamlit run`
2026-04-23 08:15:43.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.220 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.222 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.231 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.239 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [7]:
#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma','Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

,Edad,videojuego_'Mass Effect',Plataforma_'Play Station',Sexo_Hombre,Consumidor_habitual_True
0,20,1,1,1,1

In [8]:
#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

,Edad,videojuego_'Battlefield',videojuego_'Crysis',videojuego_'Dead Space',videojuego_'F1',videojuego_'Fifa',videojuego_'KOA: Reckoning',videojuego_'Mass Effect',videojuego_'Sim City',Plataforma_'Play Station',Plataforma_'Xbox',Plataforma_Otros,Plataforma_PC,Sexo_Mujer,Consumidor_habitual_True
0,20,0,0,0,0,0,0,1,0,1,0,0,0,0,1

In [9]:
#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
#data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
#data_preparada.head()

# **Predicciones**

In [10]:
#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

[18364.09746105]

In [11]:
data['Prediccion']=Y_pred
data.head()

,Edad,videojuego,Plataforma,Sexo,Consumidor_habitual,Prediccion
0,20,'Mass Effect','Play Station',Hombre,True,18364.097461

In [12]:
#predicciones finales
data

,Edad,videojuego,Plataforma,Sexo,Consumidor_habitual,Prediccion
0,20,'Mass Effect','Play Station',Hombre,True,18364.097461

In [13]:
# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 6.55%")

2026-04-23 08:15:43.514 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-23 08:15:43.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()